### ISSUE TITLE
exec() does not search ancestor directories for node_modules

### ISSUE THREAD

**Issue by platinumazure** [nzakas/shelljs-nodecli#2]
Maybe a better title for this issue might be, exec() assumes the shelljs script is being run from the package root directory.

It would be awesome if exec(), or a new function that works similarly, would look in ancestor directories until it finds a package.json, and only then look for the package to execute in a node_modules subdirectory.

If exec() is run with the cwd being a subdirectory of the package, the function will silently fall back to the global installation of the package.

**Comment by nzakas** [comment]
This isn't the way this package is intended to work, and indeed, executing Node.js binaries isn't expected to work this way.

**Comment by platinumazure** [comment]
@nzakas That's all well and good, but it would at least parallel how `require()` works, no?
